# Database connection properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scrumtool?useSSL=false
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

